import javax.swing.*;
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * booking.java
 *
 * Created on Oct 6, 2018, 1:46:10 AM
 */

/**
 *
 * @author hp pc
 */
public class booking extends javax.swing.JFrame {
Connection con;
    Statement st;
    int cost;
    /** Creates new form booking */
    public booking() {
        initComponents();
      try
   {
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=movie;user=sa;password=1234");
        st= con.createStatement();
 JOptionPane.showMessageDialog(this, "connection created");
    
  ResultSet rs=     st.executeQuery("select name from tbadd");
                  while(rs.next())
         {
            cb1.addItem( rs.getString(1));
         }
      }

           catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        cb3 = new javax.swing.JComboBox();
        cb4 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cba1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbb1 = new javax.swing.JCheckBox();
        cbc1 = new javax.swing.JCheckBox();
        cba2 = new javax.swing.JCheckBox();
        cbb2 = new javax.swing.JCheckBox();
        cbc2 = new javax.swing.JCheckBox();
        cba3 = new javax.swing.JCheckBox();
        cba4 = new javax.swing.JCheckBox();
        cbb3 = new javax.swing.JCheckBox();
        cbc3 = new javax.swing.JCheckBox();
        cbc4 = new javax.swing.JCheckBox();
        cbb4 = new javax.swing.JCheckBox();
        jb = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Movie");

        jLabel2.setText("Date");

        jLabel3.setText("Slot");

        jLabel4.setText("No. Of Tickets");

        jButton1.setText("Save & Check Seat Status");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2018-10-06", "2018-10-07", "2018-10-08" }));

        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12 PM", "03 PM", "06 PM" }));

        cb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel5.setText("Layout Of Total Seats:");

        jLabel6.setText("Gold");

        cba1.setText("A1");

        jLabel7.setText("Box");

        jLabel8.setText("Silver");

        cbb1.setText("B1");

        cbc1.setText("C1");

        cba2.setText("A2");

        cbb2.setText("B2");

        cbc2.setText("C2");

        cba3.setText("A3");

        cba4.setText("A4");
        cba4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cba4ActionPerformed(evt);
            }
        });

        cbb3.setText("B3");

        cbc3.setText("C3");

        cbc4.setText("C4");

        cbb4.setText("B4");

        jb.setText("OK");
        jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cb4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cb3, 0, 100, Short.MAX_VALUE))))
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                        .addComponent(cba1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbc1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbb1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cba2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbb2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(cbc2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cba3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cba4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbb3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbc3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbc4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbb4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cba1)
                                    .addComponent(jLabel6))
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cba4)
                                    .addComponent(cba3)
                                    .addComponent(cba2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbb4)
                                .addComponent(cbb3)
                                .addComponent(cbb2)
                                .addComponent(cbb1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbc4)
                            .addComponent(cbc3)
                            .addComponent(cbc2)
                            .addComponent(cbc1)
                            .addComponent(jLabel7))
                        .addGap(73, 73, 73)
                        .addComponent(jb)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean fetch;
try {
     String movie1 = (String) cb1.getSelectedItem();
             String date1 = (String) cb2.getSelectedItem();
            String slot1 = (String) cb3.getSelectedItem();
              String ticket1 = (String) cb4.getSelectedItem();

              if( movie1.length() == 0 || date1.length()== 0 || slot1.length()== 0 || ticket1.length()== 0)
            {
                JOptionPane.showMessageDialog(this, "fill all the boxes");
            }

            else {

st.execute("UPDATE tbbook SET movie = '"+movie1+"', date = '"+date1+"', slot = '"+slot1+"', ticket = '"+ticket1+"' WHERE id= (SELECT MAX(id) FROM tbbook) ");


             

 JOptionPane.showMessageDialog(this,"Booked");
 new bill().setVisible(true);
}
}
  catch(Exception ex)
{
      JOptionPane.showMessageDialog(this,ex.getMessage());
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cba4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cba4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cba4ActionPerformed

    private void jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionPerformed
if(cba1.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=1 ");
        JOptionPane.showMessageDialog(this,"a1 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}

if(cba2.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=2 ");
        JOptionPane.showMessageDialog(this,"a2 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}

if(cba3.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=3 ");
        JOptionPane.showMessageDialog(this,"a3 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}

if(cba4.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=4 ");
        JOptionPane.showMessageDialog(this,"a4 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}

if(cbb1.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=5 ");
        JOptionPane.showMessageDialog(this,"b1 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}

if(cbb2.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=6 ");
        JOptionPane.showMessageDialog(this,"b2 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}

if(cbb3.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=7 ");
        JOptionPane.showMessageDialog(this,"b3 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}

if(cbb4.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=8 ");
        JOptionPane.showMessageDialog(this,"b4 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}


if(cbc1.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=9 ");
        JOptionPane.showMessageDialog(this,"c1 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}

if(cbc2.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=10 ");
        JOptionPane.showMessageDialog(this,"c2 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}

if(cbc3.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=11 ");
        JOptionPane.showMessageDialog(this,"c3 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}

if(cbc4.isSelected()==true)
{
    try{
        st.execute("update tbseat set status='"+1+"' where id=12 ");
        JOptionPane.showMessageDialog(this,"c4 selected");
    }
      catch(Exception  ex)
        {
               JOptionPane.showMessageDialog(this, ex.getMessage());
   }
}



    // TODO add your handling code here:
    }//GEN-LAST:event_jbActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JComboBox cb4;
    private javax.swing.JCheckBox cba1;
    private javax.swing.JCheckBox cba2;
    private javax.swing.JCheckBox cba3;
    private javax.swing.JCheckBox cba4;
    private javax.swing.JCheckBox cbb1;
    private javax.swing.JCheckBox cbb2;
    private javax.swing.JCheckBox cbb3;
    private javax.swing.JCheckBox cbb4;
    private javax.swing.JCheckBox cbc1;
    private javax.swing.JCheckBox cbc2;
    private javax.swing.JCheckBox cbc3;
    private javax.swing.JCheckBox cbc4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb;
    // End of variables declaration//GEN-END:variables

}
